vim.keymap.set("n", "<C-b>", vim.cmd.Ex)
vim.keymap.set("i", "<C-b>", vim.cmd.Ex)
vim.keymap.set("n", "<C-q>", "<cmd>wq!<CR>")
vim.keymap.set({ "i", "n", "v" }, "<C-s>", "<Esc><cmd>w<CR>")
vim.keymap.set("n", "<C-q>q", "<cmd>q!<CR>")
vim.keymap.set("i", "<C-q>", "<cmd>wq!<CR>")
vim.keymap.set("i", "<C-q>q", "<cmd>q!<CR>")
vim.keymap.set("v", "J", ":m '>+1<CR>gv=gv")
vim.keymap.set("v", "K", ":m '<-2<CR>gv=gv")
vim.keymap.set("n", "<up>", '<cmd>echo "Use k to move!!"<CR>')
vim.keymap.set("n", "<down>", '<cmd>echo "Use j to move!!"<CR>')
vim.keymap.set("n", "<leader>cf", function()
	require("conform").format({
		lsp_format = "fallback",
	})
end)
vim.keymap.set("n", "<C-f>", "<cmd>silent !tmux neww tmux-sessionizer<CR>")
vim.keymap.set({ "n", "v" }, "<leader>y", [["+y]])
vim.keymap.set("n", "<leader>Y", [["+Y]])
