-- Map <leader>fp to open projects
vim.keymap.set("n", "<C-p>", ":ProjectFzf<CR>", { noremap = true, silent = true })
vim.keymap.set("n", "<leader>U", vim.cmd.UndotreeToggle)
vim.keymap.set({ "i", "n" }, "<C-b>", vim.cmd.Ex)
vim.keymap.set({ "i", "n", "v" }, "<C-s>", "<Esc><cmd>w<CR>")
vim.keymap.set({ "i", "n" }, "<C-q>", "<cmd>wq!<CR>")
vim.keymap.set({ "i", "n" }, "<C-q>q", "<cmd>q!<CR>")
vim.keymap.set("n", "<Esc>", "<cmd>nohlsearch<CR>")
vim.keymap.set("v", "J", ":m '>+1<CR>gv=gv")
vim.keymap.set("v", "K", ":m '<-2<CR>gv=gv")
vim.keymap.set("n", "<C-f>", "<cmd>silent !tmux neww tmux-sessionizer<CR>")
vim.keymap.set("n", "J", "mzJ`z")
vim.keymap.set("n", "<C-d>", "<C-d>zz")
vim.keymap.set("n", "<C-u>", "<C-u>zz")
vim.keymap.set("n", "n", "nzzzv")
vim.keymap.set("n", "N", "Nzzzv")
vim.keymap.set("n", "<C-k>", "<cmd>cnext<CR>zz")
vim.keymap.set("n", "<C-j>", "<cmd>cprev<CR>zz")

vim.keymap.set("n", "<leader>pnc", function()
  vim.cmd("PhpActor new_class")
end, { noremap = true, silent = true, desc = "Neue PHP Klasse erstellen" })
